### ISSUE TITLE
Does the patcher need updating for Stellaris 3.8 Pargons?

### ISSUE THREAD

**Issue by ExcerptNovela** [r0fld4nc3/Stellaris-Exe-Checksum-Patcher#8]
Hello,

Before I accidentally screw over my executable and have to verify game cache integrity or reinstall, I was just wondering if this project needs to be updated for the latest version of Stellaris or if it will work as is? I only ask because I noticed the last update was from April.

**Comment by r0fld4nc3** [comment]
Hey @ExcerptNovela 

You won't accidentally screw your executable because I create a backup of it anyways in the installation folder. If for some reason it's really screwed, then you can always delete any stellaris.exe or similar to it and then verify cache integrity, and Steam (I assume) will pull the needed files again 🙂 

The patcher still works for the current version. I have had less time now but I have been working on an update that I hope I can release soon that will introduce a few fixes and also implemented a "patch save game" feature for save games that have their achievements removed. Effectively it transforms those saves into ironman saves such that you can load them and receive the achievements that you had been either missing or want to get in the future.

Thank you for your interest!
